Video list
saketkum11/AgricVideo pull request #4
Opened 2022-05-01 17:09 UTC by saketkum11

- videolisting page
- api calls

2022-05-01 18:10 UTC, muskaanshah requested changes
User should be able to view videos of the explore page without being logged in as well.

2022-05-01 18:19 UTC, saketkum11 commented
> User should be able to view videos of the explore page without being logged in as well.

now I have removed the require auth

2022-05-01 18:19 UTC, muskaanshah approved these changes
Code is modular, easy to understand.
Just one design suggestion - dont keep the title of the video center aligned

2022-05-01 18:19 UTC, muskaanshah commented on src/Component/Nav/Navbar.jsx
> +          <a href="" class="text-dec text-color-0 text-m">
suggestion: You can use Link tags here

2022-05-01 18:25 UTC, saketkum11 commented on src/Component/Nav/Navbar.jsx
> +          <a href="" class="text-dec text-color-0 text-m">
okk sure

2022-05-01 18:43 UTC, sharathnair9999 approved these changes
Good use of utility classes. Well written code

2022-05-01 18:48 UTC, merged

2022-05-02 11:24 UTC, shubhamkumar648 commented
Good use of folder structure and functionality , good to go

2022-05-02 11:25 UTC, shubhamkumar648 reviewed
Good use of functionality and folder structure